name: "Terraform Docs"

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-docs:
    name: "Terraform Docs"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate GitHub app token
        id: github-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_CONTENT_APP_ID }}
          private_key: ${{ secrets.GH_CONTENT_APP_PEM_FILE }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.github-app-token.outputs.token }}

      - name: Setup terraform-docs
        uses: action-stars/install-tool-from-github-release@v0.2.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: terraform-docs
          repository: terraform-docs
          check_command: terraform-docs --version
          filename_format: "{name}-v{version}-{os}-{arch}.{ext}"
          version: latest

      - name: Run terraform-docs
        run: |
          terraform-docs markdown .

      - name: Commit and Push
        env:
          GH_USER_NAME: mcwarman[bot]
          GH_USER_EMAIL: 137313888+mcwarman[bot]@users.noreply.github.com
        run: |
          shopt -s globstar
          for file in **/README.md; do
            git add -- "$file"
          done
          if [ -n "$(git diff --staged)" ]; then
            git config user.name  "${GH_USER_NAME}"
            git config user.email "${GH_USER_EMAIL}"
            git commit --fixup HEAD -m "docs: terraform-docs"
            git push
          fi
